SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING OFF
GO
CREATE TABLE [dbo].[Tbl2] (
		[id]      [int] NOT NULL,
		[col]     [int] NULL,
		CONSTRAINT [PK__Tbl2__3213E83F7365484C]
		PRIMARY KEY
		CLUSTERED
		([id])
	ON [PRIMARY]
)
GO
ALTER TABLE [dbo].[Tbl2]
	WITH CHECK
	ADD CONSTRAINT [FK__Tbl2__col__276EDEB3]
	FOREIGN KEY ([col]) REFERENCES [dbo].[Tbl1] ([id])
ALTER TABLE [dbo].[Tbl2]
	CHECK CONSTRAINT [FK__Tbl2__col__276EDEB3]

GO
ALTER TABLE [dbo].[Tbl2] SET (LOCK_ESCALATION = TABLE)
GO
