SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING OFF
GO
CREATE TABLE [dbo].[Tbl1] (
		[id]      [int] NOT NULL,
		[col]     [int] NULL,
		CONSTRAINT [PK__Tbl1__3213E83F7AC9A3F8]
		PRIMARY KEY
		CLUSTERED
		([id])
	ON [PRIMARY]
)
GO
ALTER TABLE [dbo].[Tbl1] SET (LOCK_ESCALATION = TABLE)
GO
