SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING OFF
GO
CREATE TABLE [dbo].[mate] (
		[dd]     [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[mate] SET (LOCK_ESCALATION = TABLE)
GO
