SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING OFF
GO
CREATE TABLE [dbo].[PERMISOCONTRATO] (
		[PE_CODIGO]      [int] NOT NULL,
		[TRA_CODIGO]     [int] NOT NULL,
		CONSTRAINT [PK_PERMISOCONTRATO]
		PRIMARY KEY
		CLUSTERED
		([PE_CODIGO], [TRA_CODIGO])
	ON [PRIMARY]
)
GO
ALTER TABLE [dbo].[PERMISOCONTRATO] SET (LOCK_ESCALATION = TABLE)
GO
