SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING OFF
GO
CREATE TABLE [dbo].[PERMISOPAIS] (
		[PE_CODIGO]     [int] NOT NULL,
		[PA_CODIGO]     [int] NOT NULL,
		CONSTRAINT [PK_PERMISOPAIS]
		PRIMARY KEY
		CLUSTERED
		([PE_CODIGO], [PA_CODIGO])
	ON [PRIMARY]
)
GO
ALTER TABLE [dbo].[PERMISOPAIS] SET (LOCK_ESCALATION = TABLE)
GO
