SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING OFF
GO
CREATE TABLE [dbo].[RELPERSONALDEPTOS] (
		[US_CODIGO]     [smallint] NOT NULL,
		[DP_CODIGO]     [smallint] NOT NULL
)
GO
ALTER TABLE [dbo].[RELPERSONALDEPTOS] SET (LOCK_ESCALATION = TABLE)
GO
